version: '3.8'
services:
  # PHPとApache（サーバー）の箱
  php-apache:
    image: php:8.2-apache
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./my-httpd.conf:/etc/apache2/conf-enabled/my-httpd.conf
    command: >
      sh -c "sed -i 's/AllowOverride None/AllowOverride All/g' /etc/apache2/apache2.conf && apache2-foreground"

  # データベースの箱（MySQL）
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
    ports:
      - "3307:3306"