# セクションとディレクティブ
#
# <Directory>~~~</Directory>で、囲まれた部分をセクション（コンテナ）という
#
# <Directory>ディレクティブ
# 指定のディレクトリとサブディレクトリのみに適用される
# コンテキスト：サーバー設定ファイル、バーチャルホスト

# Aliasをこの<Directory>内で使うことはできない
<Directory ディレクトリ>

</Directory>

<Directory ~"正規表現">

</Directory>

# <Location> ディレクティブ
# マッチするURLでのみ適用されるディレクティブで囲む
# コンテキスト：サーバー設定ファイル、バーチャルホスト
# 基本的には、<Directory>~~~</Directory>を使うので、<Location>~~~</Location>はそういうのもあるんだな程度でOK。

<Location URLパス>

</Location>