# httpd.confファイルの開き方
# MAMP起動 -> preferences -> Server -> Document Root -> ローカルファイルの場所をOPEN -> C:\MAMP\conf\apache

# この章では実際にMAMPのhttpd.confファイルに書き込んでいく。
# 何かしかのバグで動かなくなる可能性があるので、バックアップを必ず取る

# [Alias]エイリアス
# URLをファイルシステムの位置にマップ
# コンテキスト：サーバー設定ファイル、バーチャルホスト
# DocumentRoot以外でも指定可能
# Alias　URLパス　ディレクトリ|ファイルパス
# 
# winの場合のパスの指定方法
# Alias　/alias C:/ファイル/への/パス/
# 
# Unix系（Mac、Linux）の場合のパスの指定方法
# Alias　/alias　/ファイル/への/パス/
# 
# **注意**
# URLパスの末尾は通常/をつけない。
# ディレクトリを指定する際はパスの最後に/を付ける。
# 
Alias /apache c:/MAMP/htdocs/fullstack-webdev/070_Apacheの基礎/0100_【ALIAS】URLをマッピング/start/