# [理解度チェック]
# 以下の問題文を読んで、回答を作成すること。
# 
# 問1：
# dir-testディレクトリにアクセスした際に、取得した時に取れてくるファイルを、
# file2.htmlに変更してください。

<Directory c:/MAMP/htdocs/fullstack-webdev/070_Apacheの基礎/dir-test/>
    DirectoryIndex file2.html
</Directory>


# 問2：
# dir-test/sub1ディレクトリにアクセスした際に、
#ディレクトリ内のリストが表示されるように、変更してください。

<Directory c:/MAMP/htdocs/fullstack-webdev/070_Apacheの基礎/dir-test/sub1>
    Options +Indexes
</Directory>