# ** ログの出力 **
# 
# ここではrewrite Logの出力のやり方を学ぶ
# -> Apacheのversionによって出力の設定が異なる。
<IfVersion < 2.3>
    # IfVersionは、2.3は存在しない
    # Apache ver 2.2に適用する、RewriteLogの設定方法
    LogLevel
    # Loglevelが9は、一番ログ情報が多く出力される設定
    RewriteLogLevel 9
    # ここのパスで指定されいるファイルにログが書き込まれる
    RewriteLog "C:/MAMP/logs/rewrite.log"

    # Mac,Linux
    # RewriteLog "/Applications/MAMP/logs/rewrite.log"
</IfVersion>
<IfVersion > 2.3>
    # Apache ver 2.4の場合は、上記のパスは使わないで下記の設定のみになる
    # trace8が、最もrewrite Logが出力される設定になる
    LogLevel warn rewrite:trace8
</IfVersion>
# 
# 